CREATE DATABASE TUTORIAL

GO

CREATE TABLE USUARIO
(
	ID_USUARIO INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)

GO 

INSERT INTO USUARIO VALUES(1,'ROLANDO')
INSERT INTO USUARIO VALUES(2,'ANDREA')
INSERT INTO USUARIO VALUES(3,'ANDRÉS')
INSERT INTO USUARIO VALUES(4,'ELIZABETH')

SELECT NOMBRE FROM USUARIO

GO

SELECT * 
FROM USUARIO 
WHERE NOMBRE = 'ANDREA' OR ID_USUARIO = '1'

GO
/*
DELETE FROM USUARIO WHERE NOMBRE = 'ROLANDO'
TRUNCATE TABLE USUARIO
DROP TABLE USUARIO
GO*/

UPDATE USUARIO
SET NOMBRE = 'ANDREITA'
WHERE NOMBRE = 'ANDREA'

