CREATE DATABASE TUTORIAL

GO

CREATE TABLE USUARIO
(
	ID_USUARIO INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL
)

INSERT INTO USUARIO VALUES(1,'ROLANDO')
INSERT INTO USUARIO VALUES(2,'ANDREA')
INSERT INTO USUARIO VALUES(3,'ANDRÉS')
INSERT INTO USUARIO VALUES(4,'ELIZABETH')

SELECT NOMBRE FROM USUARIO

SELECT * 
FROM USUARIO 
WHERE NOMBRE = 'ANDREA' OR ID_USUARIO = '1'

